remote_theme: pmarsceill/just-the-docs
logo: "https://user-images.githubusercontent.com/79541546/162544132-2d10c683-36bd-4e23-8ee3-de4e706430fc.png"
search_enabled: false

just_the_docs:
    ink.js:
      name: Home
    chars:
      name: Character Properties
    io:
      name: I()
